name: MongoDB Atlas

on:
  push:
    branches:
      - create-mongodb

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up MongoDB Atlas
#        uses: docker://mongo
##        with:
##          mongodb-uri: ${{ secrets.MONGODB_URI }}
        run: |
          sudo apt-get update
          sudo apt-get install gnupg
          wget -qO - https://www.mongodb.org/static/pgp/server-6.0.asc | sudo apt-key add -
          echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/6.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-6.0.list
          sudo apt-get update
          sudo apt-get install -y mongocli

      - name: Configure MongoDB CLI
        run: |
          mongocli config set org_id ${{ secrets.MONGODB_ORG_ID }}
          mongocli config set project_id ${{ secrets.MONGODB_PROJECT_ID_NEW }}
          mongocli config set public_api_key "${{ secrets.MONGODB_PUBLIC_API_KEY }}"
          mongocli config set private_api_key "${{ secrets.MONGODB_PRIVATE_KEY }}"
#          mongocli config set serviceConnectionURI "${{ secrets.MONGODB_URI_NEW }}"

      - name: Create Project
        run: |
          mongocli iam projects create --orgId ${{ secrets.MONGODB_ORG_ID }} --output json
          # Save the output of the command
          projectId=$(cat project.json | jq -r .projectId)

      - name: Create database
        run: mongocli atlas cluster create NewTest --projectId ${{ secrets.MONGODB_PROJECT_ID_NEW }} --provider AWS --region US_EAST_1 --tier M0

      - name: Verify database creation
        run: mongocli atlas clusters list --projectId ${{ secrets.MONGODB_PROJECT_ID_NEW }} --output json


#      - name: Create database
#        run: |
#          mongo ${{ secrets.MONGODB_URI_NEW }} --eval "db.createDatabase('test')"
#
#      - name: Verify database creation
#        run: |
#          mongo ${{ secrets.MONGODB_URI_NEW }} --eval "db.adminCommand('listDatabases')"
