name: Delete Branch After Merge
on:
  push:
    branches:
      - new-main

jobs:
  delete-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check if base branch is protected
        id: check_branch
        run: echo "::set-output name=protected::$(jq '.protected' <<< $(curl -s -H \"Authorization: token ${{ secrets.MY_GITHUB_TOKEN }}\" -H \"Accept: application/vnd.github.v3+json\" https://api.github.com/repos/${{ github.repository }}/branches/${{ github.base_ref }}))"
  
      - name: Delete branch
        if: steps.check_branch.outputs.protected == 'true' && github.event_name == 'push' && github.ref_type == 'branch' && github.ref != github.base_ref
        run: |
          branch_name=$(echo "${{ github.ref }}" | sed 's/refs\/heads\///g')
          curl -X DELETE -H "Authorization: token ${{ secrets.MY_GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/git/refs/heads/${branch_name}"
