#name: Delete MongoDB Atlas
#
#on:
#  push:
#    branches:
#      - create-mongodb
#
#jobs:
#  deploy:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: Set up MongoDB Atlas
#        run: |
#          sudo apt-get update
#          sudo apt-get install gnupg
#          wget -qO - https://pgp.mongodb.com/server-6.0.asc | sudo apt-key add -
#          echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/6.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-6.0.list
#          sudo apt-get update
#          sudo apt-get install -y mongodb-atlas
#
#      - name: Configure MongoDB CLI
#        run: |
#          atlas config set org_id ${{ secrets.MONGODB_ORG_ID }}
#          atlas config set project_id ${{ secrets.MONGODB_PROJECT_ID_NEW }}
#          atlas config set public_api_key "${{ secrets.MONGODB_PUBLIC_API_KEY }}"
#          atlas config set private_api_key "${{ secrets.MONGODB_PRIVATE_KEY }}"
#
#      - name: Delete database
#        run: |
#          atlas cluster delete Cluster0 --projectId ${{ secrets.MONGODB_PROJECT_ID_NEW }} --force
