#name: CI/CD Pipeline
#
#on:
#  push:
#    branches-ignore:
#      - "actions/test"
#
#jobs:
#  environmentSetup:
#    name: CI Pipeline
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        node-version: ["14.x"]
#
#    steps:
#      - uses: actions/checkout@v2
#
#      # Initialize Node.js
#      - name: Install Node.js ${{ matrix.node-version }}
#        uses: actions/setup-node@v1
#        with:
#          node-version: ${{ matrix.node-version }}
#
#  deploy:
#    name: CD Pipeline
#    runs-on: ubuntu-latest
#
#    needs: environmentSetup
#    steps:
#      - uses: actions/checkout@v2
#
#      # Install AWS CLI 2
#      - name: Install AWS CLI 2
#        run: |
#          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
#          unzip awscliv2.zip
#          sudo ./aws/install --update
#
#      # Configure AWS Credentials
#      - name: Configure AWS Credentials
#        uses: aws-actions/configure-aws-credentials@v1
#        with:
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          aws-region: eu-west-1
#
#      # Deploy Push to AWS S3
#      - name: AWS Deploy Push
#        run: |
#          npm install
#          npm run deploy
