name: Docker Build & Scout Scan

on:
  push:
    branches: [main]

env:
  IMAGE_NAME: monsters-rolodex

jobs:
  build-and-scan:
    permissions:
      actions: read
      contents: read
      security-events: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd #v4

      - name: Login to Docker Hub
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 #v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f #v7
        with:
          context: .
          load: true
          tags: ${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Scan with Docker Scout
        uses: docker/scout-action@bacf462e8d090c09660de30a6ccc718035f961e3 #v1
        with:
          command: cves
          image: ${{ env.IMAGE_NAME }}:${{ github.sha }}
          only-severities: critical,high
          exit-code: false  # do not fail the pipeline if CVEs are found
          sarif-file: scout-results.sarif

      - name: Upload SARIF to GitHub Security
        uses: github/codeql-action/upload-sarif@7851e55dc3be31ec4bcc3ef98453de2cb306e698
        if: always()  # upload even if the scan step fails
        with:
          sarif_file: scout-results.sarif

      - name: Generate SBOM with Docker Scout
        uses: docker/scout-action@bacf462e8d090c09660de30a6ccc718035f961e3 #v1
        with:
          command: sbom
          image: ${{ env.IMAGE_NAME }}:${{ github.sha }}
          format: cyclonedx
          output: sbom.json

      - name: Upload SBOM Artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a #v7
        with:
          name: image-sbom
          path: sbom.json

      # - name: Push image (only if scan passes)
      #   if: github.ref == 'refs/heads/main'
      #   run: docker push ${{ env.IMAGE_NAME }}:${{ github.sha }}
