name: Set up environment

on:
  workflow_call:

jobs:
  install-node:
    name: Install Node
    runs-on: ubuntu-latest
    strategy:
        matrix:
            node-version: [16.x]
    steps:
      # Initialize Node.js
        - name: Install Node.js
          uses: actions/setup-node@v2
          with:
            node-version: ${{ matrix.node-version }}

  install-awscli-and-terraform:
    # Install AWS CLI
    name: Install AWS CLI
    runs-on: ubuntu-latest
    needs: install-node
    steps:
      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update

    # Configure AWS CLI
      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

    # Install Terraform
      - name: Install Terraform
        run: |
          sudo apt-get update
          sudo apt-get install -y gnupg software-properties-common curl unzip
          wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt update && sudo apt install terraform
