name: SkillGuard Scan
on: [push, pull_request]

jobs:
  security_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run SkillGuard Security Scan
        uses: ossafrica/skillguard@8b33996166f0991d7897d49575162158261172a0 #v0.6.0
        with:
          # path: './my-skills'
          threshold: 70
          verbose: true
