name: Testing

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Extract branch name
        id: branch-name
        run: |
          # branch=$(git branch --show-current)
          echo "{branch}={$(git branch --show-current)}" >> $GITHUB_OUTPUT

      - name: Print branch name
        run: echo "${{ steps.branch-name.outputs.branch }}"
