name: Deploy Env

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Extract branch name
        id: branch-name
        run: |
          echo "::set-output name=branch::$(git branch --show-current)"

      - name: Print branch name
        run: echo "Branch:${{ steps.branch-name.outputs.branch }}"
        
