#name: Destroy Env
#
#on:
#  pull_request
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v3
#
#      - name: Build Test
#        uses: ./.github/workflows/test.yml
#
#      - name: Print
#        run:  echo "Caleb"
#